### ISSUE TITLE
Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by aalbox** [DashCruft/Discord.JS-meme#5]
steps to produce:
1. type the prefix along with a random word other than the cmds ex: "!a"

**Comment by DashCruft** [comment]
Hey aalbox!
Can you be more specific about this? I need more clarification about the steps to produce and I want a full log error with a source code attached.
Use a bin if possible to reduce flooding.

Regards, DashCruft

**Comment by aalbox** [comment]
`ReferenceError: bot is not defined
    at Client.<anonymous> (/home/runner/box2/index.js:26:74)
    at Client.emit (events.js:315:20)
    at Client.EventEmitter.emit (domain.js:483:12)
    at MessageCreateAction.handle (/home/runner/box2/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/box2/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/box2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/box2/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/box2/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/box2/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)`
    this is the error
    
steps to produce:
type the prefix with a non defined command
ex: 
![image](https://user-images.githubusercontent.com/76613776/103525594-22b8fe80-4e88-11eb-868e-442a095dd1d9.png)

**Comment by aalbox** [comment]
the code is the same as yours

**Comment by DashCruft** [comment]
You haven't defined bot. Maybe try replacing "bot" with "client" in your code.

**Comment by strange-idiot** [comment]
const Discord = require('discord.js');
const client = new Discord.Client();

try this @aalbox

**Comment by DashCruft** [comment]
I'm going to close this since we haven't heard anything from the ticket creator!

Open a new issue in case a problem occurs.
